name: RUSTSEC Bot
description: Creates issues from RUSTSEC advisories

inputs:
  labels:
    description: Comma-separated list of labels to add to the issue
    required: true
    default: rust,security

  mode:
    description: |
      'report' to create issues from RUSTSEC advisories; or 'check' to run without creating issues
    required: true
    default: report

  token:
    description: GitHub token with the 'issues:write' scope
    required: true
    default: ${{ github.token }}

  version:
    description: The version of rustsecbot to use
    required: false
    default: v0.2.0

  deny-version:
    description: The version of cargo-deny to use
    required: false
    default: 0.11.4

outputs:
  opened:
    description: List of issues/advisories that were opened

runs:
  using: composite
  steps:
    - name: Install cargo-deny
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.3 -fsSL https://github.com/EmbarkStudios/cargo-deny/releases/download/${{ inputs.deny-version }}/cargo-deny-${{ inputs.deny-version }}-x86_64-unknown-linux-musl.tar.gz \
          | tar -xzv -C /usr/local/bin --strip-components=1;
        cargo-deny --version

    - name: Install rustsecbot
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.3 -fsSLo /usr/local/bin/rustsecbot "https://github.com/olix0r/rustsecbot/releases/download/release%2F${{ inputs.version }}/rustsecbot-x86_64-unknown-linux-gnu"
        chmod 755 /usr/local/bin/rustsecbot
        rustsecbot --version

    - name: Run rustsecbot
      shell: bash
      run: |
        rustsecbot \
          --github-token "${{ inputs.token }}" \
          --labels "${{ inputs.labels }}" \
          --mode "${{ inputs.mode }}"
