name: RUSTSEC

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/rustsec.yml
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  rustsecbot:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: olix0r/rustsecbot@v1
